#!/usr/bin/env bash
# psai — Pandora AI Stack installer for macOS and Linux.
# Open WebUI + OpenHands + SearXNG (+ Forgejo, Qdrant, MCP) behind Caddy,
# with two independent egress proxies. Single-node or master+agents fleet.
#
# Pure bash 3.2 compatible (no associative arrays, no ${var^^}, no mapfile).
# NOTE: this single file is ASSEMBLED from lib/*.sh by ./build.sh.
# Edit the modules in lib/ and re-run ./build.sh — do not edit this file by hand.
set -Eeuo pipefail

STACK_VERSION="1.0.2"
STACK_CHANNEL="beta"                  # release channel; shown as "v1.0.2 beta"
STACK_VERSION_TAG="v1.0.2_beta"       # git/version tag form
PRODUCT_NAME="Pandora AI Stack"               # product name (post-install + help)
# shellcheck disable=SC2034
INSTALLER_TITLE="Pandora AI Stack"
MGMT_NAME="psai"                  # fixed name of the management command/script
UPDATE_AVAILABLE="false"             # true -> HOST status dot turns yellow
DEFAULT_STACK_NAME="psai"
DEFAULT_ADMIN_USER="admin"
DEFAULT_DOMAIN_ZONE="lan"
DEFAULT_CERT_YEARS="3"
DEFAULT_GIT_SSH_PORT="2222"

# Local deployments may skip domains entirely: NO_DOMAIN=true serves each service on a
# distinct loopback HTTP port (http://localhost:PORT) — no /etc/hosts, no local CA.
NO_DOMAIN="${PSAI_NO_DOMAIN:-false}"
# Dual access (local only): serve the .lan domains over the local-CA HTTPS AND publish each
# service on a loopback port — reach the stack both ways. `install --defaults` turns this on.
DUAL_ACCESS="${PSAI_DUAL:-false}"
PORT_PSAI="${PSAI_PORT_PSAI:-8080}"          # Open WebUI
PORT_AGENTS="${PSAI_PORT_AGENTS:-8081}"  # OpenHands
PORT_GIT="${PSAI_PORT_GIT:-8082}"        # Forgejo web
PORT_QDRANT="${PSAI_PORT_QDRANT:-8083}"  # Qdrant dashboard

# Public repo entry points. RAW must point to the raw .sh (self-update + one-line install).
REPO_RAW_URL="${PSAI_RAW_URL:-https://raw.githubusercontent.com/pandora-ai-stack/psai/main/psai.sh}"
# shellcheck disable=SC2034  # documented public repo web URL
REPO_WEB_URL="${PSAI_WEB_URL:-https://github.com/pandora-ai-stack/psai}"
REPO_VERSIONS_URL="${PSAI_VERSIONS_URL:-https://raw.githubusercontent.com/pandora-ai-stack/psai/main/versions.json}"  # self-update trust manifest
# Pinned SSH PUBLIC key — the trust anchor for the self-update manifest (versions.json).
# Releases sign versions.json with the matching SSH key (YubiKey-resident) via
# `ssh-keygen -Y sign`; self-update verifies with `ssh-keygen -Y verify` against THIS key.
# Empty = self-update fails closed (refuses). Identity + namespace must match the signer.
UPDATE_SIGN_PUBKEY="${UPDATE_SIGN_PUBKEY:-ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJoNvCVTUo1rjPf8BDLyyAAEjLfJX5GmmyzO9mx2jFtl}"
UPDATE_SIGN_ID="${UPDATE_SIGN_ID:-adam@merovingian.io}"
UPDATE_SIGN_NS="${UPDATE_SIGN_NS:-psai-versions}"

# ── Component images ───────────────────────────────────────────────────────
# Open WebUI: latest (per request). OpenHands: PINNED (an unpinned agent runtime
# can change behaviour on any upstream push) — select_openhands_image resolves
# the registry. SearXNG/Qdrant we now own fully (no upstream repo), so we control
# their healthchecks and may track latest.
OPENWEBUI_IMAGE="${OPENWEBUI_IMAGE:-ghcr.io/open-webui/open-webui:main}"
OPENHANDS_VERSION="${OPENHANDS_VERSION:-1.8.0}"
OPENHANDS_IMAGE_DEFAULT="${OPENHANDS_IMAGE:-}"
OPENHANDS_SANDBOX_IMAGE_SUFFIX="openhands_sandbox:1.0.2"
SEARXNG_IMAGE="${SEARXNG_IMAGE:-searxng/searxng:latest}"
QDRANT_IMAGE="${QDRANT_IMAGE:-qdrant/qdrant:latest}"
FORGEJO_IMAGE="${FORGEJO_IMAGE:-codeberg.org/forgejo/forgejo:15}"
# Pinned: Caddy 2.11 changed basic_auth hash handling (expects base64), which breaks
# the classic `caddy hash-password` bcrypt string written into the Caddyfile. 2.9 keeps
# the stable behaviour. Bump deliberately + re-test basic_auth on every Caddy upgrade.
CADDY_IMAGE="${CADDY_IMAGE:-caddy:2.9-alpine}"
HTTPD_IMAGE="${HTTPD_IMAGE:-httpd:2.4-alpine}"   # used for htpasswd bcrypt
ALPINE_IMAGE="${ALPINE_IMAGE:-alpine:3.20}"
MCP_IMAGE="${MCP_IMAGE:-python:3.12-alpine}"     # base for the local MCP stub
# Nested Docker for the hardened OpenHands isolation mode (dind).
DIND_IMAGE="${DIND_IMAGE:-docker:27-dind}"
# RAG-plus stack: local embeddings + reranker (Infinity — OpenAI-compatible, serves BOTH
# /v1/embeddings and reranking; CPU + arm64) and a document-ingest layer (Docling primary,
# Apache Tika fallback) that turns PDF/DOCX/tables/formulas into structured text.
INFINITY_IMAGE="${INFINITY_IMAGE:-michaelf34/infinity:latest}"
# Docling's GHCR "latest" image has been observed to stall on macOS/Colima while
# the official Quay CPU variant continues pulling. Keep this overridable.
DOCLING_IMAGE="${DOCLING_IMAGE:-quay.io/docling-project/docling-serve-cpu:latest}"
TIKA_IMAGE="${TIKA_IMAGE:-apache/tika:latest}"
# Agent memory backends (PSAI_MEMORY). cognee = self-host graph+vector memory (embedded
# stores, no extra DB); graphiti = temporal graph on FalkorDB; mem0 = cloud.
COGNEE_IMAGE="${COGNEE_IMAGE:-cognee/cognee-mcp:main}"
GRAPHITI_IMAGE="${GRAPHITI_IMAGE:-zepai/knowledge-graph-mcp:standalone}"
FALKORDB_IMAGE="${FALKORDB_IMAGE:-falkordb/falkordb:latest}"
# Bundled local LLM (PSAI_LLM=ollama): a local OpenAI-compatible endpoint at
# http://ollama:11434/v1 used by the memory backend (and offered to chat). LM Studio and
# cloud are NOT bundled — they're "bring your own" external endpoints via *_LLM_URL.
OLLAMA_IMAGE="${OLLAMA_IMAGE:-ollama/ollama:latest}"
# Docker MCP Gateway (PSAI_MCP_GATEWAY): one verified, isolated, signature-checked endpoint for
# a curated allowlist of MCP tool servers (instead of a pile of ad-hoc servers). Needs the
# Docker socket to spawn the server containers — host-level control, so trusted hosts only.
MCP_GATEWAY_IMAGE="${MCP_GATEWAY_IMAGE:-docker/mcp-gateway:latest}"
MCPO_IMAGE="${MCPO_IMAGE:-ghcr.io/open-webui/mcpo:main}"  # SSE-MCP → OpenAPI bridge for Open WebUI chat tools
# LiteLLM model gateway (PSAI_LLM_GATEWAY): one OpenAI-compatible endpoint in front of every
# model — routing, fallback, caching, per-key budgets. Langfuse (PSAI_EVAL): traces + evals.
LITELLM_IMAGE="${LITELLM_IMAGE:-ghcr.io/berriai/litellm:main-stable}"
LANGFUSE_IMAGE="${LANGFUSE_IMAGE:-langfuse/langfuse:2}"   # v2 = single Postgres (v3 needs clickhouse)
LANGFUSE_DB_IMAGE="${LANGFUSE_DB_IMAGE:-postgres:16-alpine}"

# Egress gateway images (shared by proxy-stack and proxy-web).
TOR_IMAGE="${TOR_IMAGE:-dperson/torproxy:latest}"
XRAY_IMAGE="${XRAY_IMAGE:-ghcr.io/xtls/xray-core:latest}"
WIREGUARD_IMAGE="${WIREGUARD_IMAGE:-lscr.io/linuxserver/wireguard:latest}"
HTTP_SIDECAR_IMAGE="${HTTP_SIDECAR_IMAGE:-monokal/tinyproxy:latest}"
ADGUARDVPN_IMAGE="${ADGUARDVPN_IMAGE:-adguard/adguardvpn-cli:latest}"
TAILSCALE_IMAGE="${TAILSCALE_IMAGE:-tailscale/tailscale:latest}"

SCRIPT_PATH="${BASH_SOURCE[0]}"
# Resolve through symlinks so SCRIPT_DIR is the script's REAL directory. The
# 'psai' command on PATH is a symlink into the stack's bin/; without this we
# would land in /opt/homebrew/bin and never find .stack.env (→ wrong menu/lang).
_psai_resolve_dir() {
  local src="$1" dir=""
  while [ -h "$src" ]; do
    dir="$(cd -P "$(dirname "$src")" 2>/dev/null && pwd)" || break
    src="$(readlink "$src")" || break
    case "$src" in /*) ;; *) src="$dir/$src" ;; esac
  done
  cd -P "$(dirname "$src")" 2>/dev/null && pwd || dirname "$src"
}
SCRIPT_DIR="$(_psai_resolve_dir "$SCRIPT_PATH")"
CONFIG_FILE=""
SEVENZIP_BIN=""
OS_TYPE="unknown"
ARCH_TYPE="unknown"
DOCKER_SOCK=""
# Pinned docker context (e.g. "colima"). When a host runs BOTH Colima and Docker Desktop,
# the ambient context can flip between runs and the installer would manage the wrong daemon.
# Captured at install (the context that was actually used) and re-exported on every run so
# all docker/compose commands target the same daemon. Empty = use the ambient context.
DOCKER_CONTEXT_PIN="${PSAI_DOCKER_CONTEXT:-}"

# Don't let `brew install` stall for minutes on "Auto-updating Homebrew…" (a common hang
# in the env-setup step). The installer only needs a few formulae from the cached taps.
export HOMEBREW_NO_AUTO_UPDATE=1

# ── UI state ───────────────────────────────────────────────────────────────
UI_LANG="${PSAI_LANG:-}"               # ru | en
LANG_FROM_ENV="0"; [ -n "$UI_LANG" ] && LANG_FROM_ENV="1"
LANG_STORE="$HOME/.config/psai/lang"   # remembered language before any stack exists
NONINTERACTIVE="${PSAI_NONINTERACTIVE:-0}"
ASSUME_DEFAULTS="${PSAI_ASSUME_DEFAULTS:-0}"

# ── Runtime config (loaded from .stack.env or collected interactively) ──────
STACK_NAME=""
SAFE_STACK_NAME=""
STACK_DIR=""
ADMIN_USER=""
ADMIN_PASSWORD_PLAIN="${PSAI_ADMIN_PASSWORD:-}"  # user-chosen admin password (never on disk);
                                                # env override so `install --defaults` can set it
                                                # (the interactive prompt overrides this)

# Deployment shape.
NODE_MODE="${PSAI_NODE_MODE:-single}"  # single | multi  (multi = master + agent worker nodes)
# Deployment profile: local = trusted LAN (local CA), public = internet-facing (ACME/own cert).
DEPLOY_PROFILE="${PSAI_DEPLOY:-local}"  # local | public

# Components.
ENABLE_OPENWEBUI="${PSAI_OPENWEBUI:-true}"   # primary chat UI
ENABLE_AGENTS="${PSAI_AGENTS:-true}"          # OpenHands agents
ENABLE_SEARCH="${PSAI_SEARCH:-true}"          # SearXNG, wired into Open WebUI + agents
ENABLE_GIT="${PSAI_GIT:-true}"                # Forgejo (configure on first login)
ENABLE_QDRANT="${PSAI_QDRANT:-false}"         # shared vector memory (Open WebUI + agents)
ENABLE_MCP="${PSAI_MCP:-false}"               # own MCP server (stub) — comes up with Qdrant
ENABLE_EMBEDDINGS="${PSAI_EMBEDDINGS:-false}" # local embeddings -> auto-index into Qdrant
EMBEDDINGS_MODEL="${EMBEDDINGS_MODEL:-BAAI/bge-small-en-v1.5}"
# External semantic embeddings: point Open WebUI RAG + the MCP server at an
# OpenAI-compatible /embeddings endpoint instead of the built-in/hash encoder.
EMBED_URL="${PSAI_EMBED_URL:-}"               # e.g. http://host:8080/v1 (empty = built-in)
EMBED_MODEL="${PSAI_EMBED_MODEL:-}"           # model id for the external embedder
EMBED_API_KEY="${PSAI_EMBED_API_KEY:-}"       # bearer key for the external embedder (if any)
# RAG mode: off (no vector store) | basic (Qdrant + Open WebUI built-in embeddings) | plus
# (Qdrant + local embed/rerank service + Docling/Tika ingest + reranking; hybrid opt-in).
# 'plus' resolves the flags below and points Open WebUI RAG + the MCP memory at the local
# OpenAI-compatible embedder — see resolve_rag_mode().
RAG_MODE="${PSAI_RAG:-off}"                    # off | basic | plus
# Agent memory backend: stub (built-in keyword MCP) | cognee (self-host graph+vector) |
# graphiti (temporal graph on FalkorDB) | mem0 (cloud) | none. cognee/graphiti call an LLM to
# build the graph — point them at ANY OpenAI-compatible endpoint (cloud, or a local Ollama/
# LiteLLM); without a key they start but graph ops fail.
MEMORY_MODE="${PSAI_MEMORY:-stub}"             # stub | cognee | graphiti | mem0 | none
MEMORY_LLM_URL="${PSAI_MEMORY_LLM_URL:-}"      # OpenAI-compatible base for the memory LLM
MEMORY_LLM_KEY="${PSAI_MEMORY_LLM_KEY:-}"      # LLM API key for cognee/graphiti
MEMORY_LLM_MODEL="${PSAI_MEMORY_LLM_MODEL:-gpt-4o-mini}"
MEM0_API_KEY="${PSAI_MEM0_API_KEY:-}"          # mem0 cloud key
MEM0_MCP_URL="${PSAI_MEM0_MCP_URL:-}"          # mem0 cloud MCP SSE url (when PSAI_MEMORY=mem0)
MEMORY_PORT="8000"                            # internal memory MCP port (reached as memory:8000)
# Bundled local LLM (Ollama). none = use an external endpoint (LM Studio/cloud) via *_LLM_URL.
LOCAL_LLM="${PSAI_LLM:-none}"                   # none | ollama
OLLAMA_MODEL="${PSAI_OLLAMA_MODEL:-llama3.2:3b}"          # chat/memory model (CPU-friendly default)
GPU_MODE="${PSAI_GPU:-}"                        # '' = autodetect at install | nvidia | none
OLLAMA_EMBED_MODEL="${PSAI_OLLAMA_EMBED_MODEL:-nomic-embed-text}"  # embeddings when no Infinity
OLLAMA_PULL_VIA_PROXY="${PSAI_OLLAMA_PULL_VIA_PROXY:-false}"       # true = model pulls via proxy-stack
# Docker MCP Gateway — verified tool servers for the agents over one SSE endpoint.
MCP_GATEWAY="${PSAI_MCP_GATEWAY:-false}"        # true → run the gateway (trusted hosts only)
LLM_GATEWAY="${PSAI_LLM_GATEWAY:-false}"        # LiteLLM proxy (routing/fallback/cache/budgets)
ENABLE_EVAL="${PSAI_EVAL:-false}"               # Langfuse — LLM traces + evals + prompt mgmt
# Allowlist of catalog servers. Default = safe, credential-free, no host-FS (fetch + Context7
# version-specific docs). Add filesystem/git/playwright/etc. deliberately (they need scoping).
MCP_GATEWAY_SERVERS="${PSAI_MCP_GATEWAY_SERVERS:-fetch,context7}"
MCP_GATEWAY_PORT="8811"                        # internal SSE port (reached as mcp-gateway:8811)
ENABLE_EMBED_SVC="${PSAI_EMBED_SVC:-false}"    # local Infinity embeddings+reranker service
ENABLE_INGEST="${PSAI_INGEST:-false}"          # Docling + Tika document ingest
RAG_HYBRID="${PSAI_RAG_HYBRID:-false}"         # Open WebUI hybrid (dense+BM25) — opt-in (debated)
EMBED_SVC_MODEL="${PSAI_EMBED_SVC_MODEL:-BAAI/bge-m3}"        # local embedding model (multilingual)
RERANK_MODEL="${PSAI_RERANK_MODEL:-BAAI/bge-reranker-v2-m3}"  # reranker model (multilingual)
EMBED_SVC_PORT="7997"                         # internal Infinity port (reached as embed:7997)
# PentestGPT (GreyDGL/PentestGPT) — AUTHORIZED security testing only. Opt-in, off by
# default, isolated (own container, egress via the proxies). Needs an LLM API key.
ENABLE_PENTEST="${PSAI_PENTEST:-false}"
PENTEST_PY_IMAGE="${PENTEST_PY_IMAGE:-python:3.11-slim}"
AGENTS_DOCKER="false"                         # let OpenHands drive host Docker (deploy containers)
AGENT_WEB="${PSAI_AGENT_WEB:-true}"            # OpenHands reachable on the web (else CLI/WG only)
OPENHANDS_LLM_MODEL="${PSAI_OH_MODEL:-}"       # preset model for OpenHands (multi-node)
CA_TRUSTED="false"

# OpenHands Docker mode: host (simplest) | rootless (Linux) | dind (nested, hardened).
# Default resolves to dind on public/multi (untrusted) deployments unless the operator
# pinned a mode via PSAI_OH_MODE — see resolve_oh_mode().
OPENHANDS_DOCKER_MODE="${PSAI_OH_MODE:-host}"
OH_MODE_FROM_ENV=0; [ -n "${PSAI_OH_MODE:-}" ] && OH_MODE_FROM_ENV=1

# ── Security profile ───────────────────────────────────────────────────────
# strict  = max: seal(manual+RAM) + CIS + sshd + upgrades + firewall + watchdog
#           + disable-public-SSH (public/multi) + fail2ban.
# default = seal(auto) + CIS + sshd + upgrades.   none = baseline container hardening only.
# Every capability below is INDIVIDUALLY toggleable after install.
SECURITY_PROFILE="${PSAI_PROFILE:-default}"   # strict | default | none
SEC_SEAL="${PSAI_SEC_SEAL:-}"          # ''|true|false  — secrets at-rest encryption
SEC_FIREWALL="${PSAI_SEC_FIREWALL:-}"  # host firewall
SEC_WATCHDOG="${PSAI_SEC_WATCHDOG:-}"  # health watchdog daemon
SEC_CIS="${PSAI_SEC_CIS:-}"            # CIS kernel sysctls + sshd hardening + upgrades
SEC_NOSSH="${PSAI_SEC_NOSSH:-}"        # disable public SSH (WG-only) — public/multi
SEC_FAIL2BAN="${PSAI_SEC_FAIL2BAN:-}"  # fail2ban (public)
SEC_TPM="${PSAI_SEC_TPM:-}"            # TPM auto-unseal (resolve_security_profile seeds from VAULT_TPM)

# Secrets seal/unseal. auto = key in a host keyfile (auto-unseal on start);
# manual = passphrase prompted on every start (nothing stored); RAM-unseal when strict.
SEAL_ENABLED="${PSAI_SEAL:-false}"
SEAL_MODE="${PSAI_SEAL_MODE:-auto}"    # auto | manual
SEAL_PASS_PLAIN=""                     # transient manual passphrase (never persisted)

# ── Domains / TLS ──────────────────────────────────────────────────────────
DOMAIN_ZONE=""
DOMAIN_BASE=""
PSAI_DOMAIN=""           # Open WebUI (psai.<zone>)
AGENTS_DOMAIN=""       # OpenHands
GIT_DOMAIN=""          # Forgejo web
GIT_SSH_HOST=""
GIT_SSH_PORT=""
QDRANT_DOMAIN=""       # Qdrant dashboard (optional)
CERT_YEARS=""
# Public TLS: le = Let's Encrypt/ACME, own = bring-your-own cert, self = IP + self-signed.
TLS_MODE="${PSAI_TLS_MODE:-le}"        # le | own | self
OWN_CERT_PATH=""
OWN_KEY_PATH=""
PUBLIC_DOMAIN="${PSAI_PUBLIC_DOMAIN:-}"
ACME_EMAIL="${PSAI_ACME_EMAIL:-}"
ENABLE_FAIL2BAN="false"
OPENHANDS_IMAGE=""

# ── Two independent egress proxies ─────────────────────────────────────────
# proxy-stack : ALL model traffic — every LLM API call the apps make (CLOUD *and*
#               LOCAL models) + component pulls/updates. Local models stay direct
#               by default (a Tor hop can't reach a LAN/localhost model); set
#               PSAI_ROUTE_LOCAL_LLM=true to route them through proxy-stack too.
# proxy-web   : the WEB WORKER — all user/working requests to the network
#               (SearXNG search + the OpenHands sandbox's browsing/fetch).
# Both default 'none' (DIRECT — no container, no hop). Presets: stack→tor, web→wireguard.
EGRESS_STACK="${PSAI_EGRESS_STACK:-none}"   # none | tor | wireguard | vless | adguardvpn | tailscale
EGRESS_WEB="${PSAI_EGRESS_WEB:-none}"       # same modes
STACK_VIA_PROXY="${PSAI_STACK_VIA_PROXY:-true}"   # apps' LLM API egress routes via proxy-stack
WEB_VIA_PROXY="${PSAI_WEB_VIA_PROXY:-true}"       # search + sandbox route via proxy-web
ROUTE_LOCAL_LLM="${PSAI_ROUTE_LOCAL_LLM:-false}"  # also route LOCAL model calls via proxy-stack
# Proxy = firewall/router controls. The tunnel modes (wireguard/…) become real
# firewalls: DNS pinned to one resolver, a kill-switch that drops all egress not
# going through the tunnel (no leak if it drops), and an optional CIDR allow-list.
PROXY_DNS="${PSAI_PROXY_DNS:-1.1.1.1}"            # pin the tunnel's DNS resolver
PROXY_KILLSWITCH="${PSAI_PROXY_KILLSWITCH:-true}" # drop egress if the tunnel is down
PROXY_ALLOW_CIDR="${PSAI_PROXY_ALLOW_CIDR:-}"     # optional egress allow-list (space-sep CIDRs)
PROXY_ALLOW_FQDN="${PSAI_PROXY_ALLOW_FQDN:-}"     # optional egress allow-list (space-sep domains)

# Zero-disk runtime secrets: render .runtime.env onto tmpfs (Linux) so reversible
# session keys never touch the SSD. Falls back to the (already 0600) disk file elsewhere.
RUNTIME_TMPFS="${PSAI_RUNTIME_TMPFS:-true}"
# TPM-sealed vault passphrase (Linux, tpm2-tools): seal the passphrase to the machine's
# TPM so the vault auto-unseals on that hardware only. Off by default.
VAULT_TPM="${PSAI_VAULT_TPM:-false}"
# Full ptrace lockdown (kernel.yama.ptrace_scope=3): blocks even root from ptrace-ing
# into the vault to read secrets. Irreversible until reboot, disables all debugging —
# opt-in. The CIS baseline already sets ptrace_scope=1.
VAULT_PTRACE_LOCKDOWN="${PSAI_PTRACE_LOCKDOWN:-false}"
EGRESS_STACK_HTTP=""   # computed: http://proxy-stack:<port>
EGRESS_WEB_HTTP=""     # computed: http://proxy-web:<port>
EG_SANDBOX_HTTP=""     # computed: sandbox reaches proxy-web via host.docker.internal
EG_HOST_WEB_PORT="18118"

# Log retention (stack + docker + system). Format: <N><d|w|m|y>, e.g. 6m, 30d, 2y.
LOG_RETENTION="${PSAI_LOG_RETENTION:-6m}"

# ── Multi-node fleet (master_node_0 + agent_worker_<N> over WireGuard) ────
# master_node_0 = WG .1 (control plane: management + state collection).
# agent_worker_<N> = WG .{2+N}: autonomous
# OpenHands hosts, reachable only inside WG; web access opt-in. Shared Qdrant on
# the master gives every agent + Open WebUI one vector store.
ISOLATE_AGENTS="${PSAI_ISOLATE_AGENTS:-false}"
ISOLATE_GIT="${PSAI_ISOLATE_GIT:-false}"        # move Forgejo onto agent_worker_0
SHARED_MEMORY="${PSAI_SHARED_MEMORY:-false}"    # share master Qdrant with agents over WG
AGENT_EGRESS="${PSAI_AGENT_EGRESS:-tor}"        # agent_worker proxy-web egress
AGENT_INDEX="${PSAI_AGENT_INDEX:-0}"
AGENT_DOMAIN="${PSAI_AGENT_DOMAIN:-}"
AGENT_SUB="${PSAI_AGENT_SUB:-agents}"
AGENT_GIT_SUB="${PSAI_AGENT_GIT_SUB:-git}"
AGENT_ACME_EMAIL="${PSAI_AGENT_ACME_EMAIL:-}"
AGENT_SERVERS="${AGENT_SERVERS:-}"             # registry: "idx:public_ip:wg_ip:domain" the master knows
SSH_FAILBACK_MIN="${PSAI_SSH_FAILBACK_MIN:-10}" # boot SSH window before auto-lockdown
# External KMS node: when set (its WG IP), the keys store + KMS daemon live on a
# separate node, not the master. Empty = KMS co-located on the master (default).
# KMS_SSH_USER/KMS_SSH_KEY are how the master reaches that node's keys store (persisted
# by save_config so the setting survives; kms_node_ssh reads them).
KMS_HOST="${PSAI_KMS_HOST:-}"
KMS_SSH_USER="${KMS_SSH_USER:-}"
KMS_SSH_KEY="${KMS_SSH_KEY:-}"
AGENT_PUBLIC_IP=""
AGENT_WG_IP=""
REMOTE_WG_NET="${REMOTE_WG_NET:-10.99.0}"      # /24; master=.1  agent_<N>=.{2+N}
REMOTE_WG_PORT="${REMOTE_WG_PORT:-51820}"
RA_HOST="" RA_PORT="22" RA_USER="root"
