# ───────────────────────────── compose generator ─────────────────────────────
# One self-contained docker-compose.yml (no upstream repo). Services are appended
# conditionally so disabled components never appear.

COMPOSE_FILE() { printf '%s/compose/docker-compose.yml' "$STACK_DIR"; }

compose_header() {
  cat > "$(COMPOSE_FILE)" <<EOF
# Generated by psai — do not edit by hand (regenerated on rebuild/reconfig).
name: "$SAFE_STACK_NAME"
services:
EOF
}

# Dual access = domains AND loopback ports (local only). Loopback port publishes for Caddy.
dual_access() { [ "${DUAL_ACCESS:-false}" = "true" ] && ! no_domain; }
caddy_loopback_ports() {
  local p=""
  { [ "$ENABLE_OPENWEBUI" = "true" ] || [ "$ENABLE_AGENTS" = "true" ]; } && p="$p
      - \"127.0.0.1:${PORT_PSAI}:${PORT_PSAI}\""
  [ "$ENABLE_OPENWEBUI" = "true" ] && [ "$ENABLE_AGENTS" = "true" ] && p="$p
      - \"127.0.0.1:${PORT_AGENTS}:${PORT_AGENTS}\""
  [ "$ENABLE_GIT" = "true" ]    && p="$p
      - \"127.0.0.1:${PORT_GIT}:${PORT_GIT}\""
  [ "$ENABLE_QDRANT" = "true" ] && p="$p
      - \"127.0.0.1:${PORT_QDRANT}:${PORT_QDRANT}\""
  printf '%s' "$p"
}

compose_caddy() {
  local dep="" ports_block=""
  [ "$ENABLE_OPENWEBUI" = "true" ] && dep="$dep
      openwebui:
        condition: service_healthy"
  [ "$ENABLE_AGENTS" = "true" ]    && dep="$dep
      openhands:
        condition: service_started"
  [ "$ENABLE_GIT" = "true" ]       && dep="$dep
      forgejo:
        condition: service_started"
  [ "$ENABLE_QDRANT" = "true" ]    && dep="$dep
      qdrant:
        condition: service_started"
  [ -n "$dep" ] && dep="    depends_on:$dep"
  local ports='      - "80:80"
      - "443:443"'
  if no_domain; then
    ports="$(caddy_loopback_ports)"          # loopback ports only; no 80/443
  elif dual_access; then
    ports="$ports$(caddy_loopback_ports)"    # domains (80/443) AND loopback ports
  fi
  [ -n "$ports" ] && ports_block="    ports:
$ports"
  cat >> "$(COMPOSE_FILE)" <<EOF
  caddy:
    image: $CADDY_IMAGE
    container_name: ${SAFE_STACK_NAME}-caddy
    restart: unless-stopped
    security_opt: [ "no-new-privileges:true" ]
$ports_block
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ../caddy/data:/data
      - ../caddy/config:/config
      - ../secrets/certificates:/certs:ro
$dep
EOF
}

compose_openwebui() {
  [ "$ENABLE_OPENWEBUI" = "true" ] || return 0
  local search="" vec="" model_update_env="" owui_url cors_origins cookie_secure
  owui_url="$(openwebui_url)"
  cors_origins="$(build_allowed_origins)"
  cookie_secure="$(openwebui_cookie_secure)"
  if [ "$ENABLE_SEARCH" = "true" ]; then
    search="      - ENABLE_WEB_SEARCH=True
      - WEB_SEARCH_ENGINE=searxng
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
      - WEB_SEARCH_RESULT_COUNT=4
      - WEB_SEARCH_CONCURRENT_REQUESTS=10"
  fi
  if [ "$ENABLE_QDRANT" = "true" ]; then
    vec="      - VECTOR_DB=qdrant
      - QDRANT_URI=http://qdrant:6333"
    if [ -n "${EMBED_URL:-}" ]; then
      # External semantic embeddings: OpenAI-compatible endpoint.
      vec="$vec
      - RAG_EMBEDDING_ENGINE=openai
      - RAG_OPENAI_API_BASE_URL=$EMBED_URL
      - RAG_EMBEDDING_MODEL=${EMBED_MODEL:-$EMBEDDINGS_MODEL}"
    elif [ "$ENABLE_EMBEDDINGS" = "true" ]; then
      # Built-in sentence-transformers (runs in this container; arm64 + x86, no separate
      # image, offline). RAG_EMBEDDING_ENGINE empty = local.
      vec="$vec
      - RAG_EMBEDDING_ENGINE=
      - RAG_EMBEDDING_MODEL=$EMBEDDINGS_MODEL"
    fi
    # RAG-plus: a CrossEncoder reranker (the biggest precision lever) + optional hybrid
    # (dense+BM25). Hybrid is opt-in — its validity is debated and Open WebUI's hybrid path
    # has been flaky across releases — so reranking carries the win on its own by default.
    if [ "${RAG_MODE:-off}" = "plus" ] || [ "${ENABLE_EMBED_SVC:-false}" = "true" ]; then
      [ -n "${RERANK_MODEL:-}" ] && vec="$vec
      - RAG_RERANKING_MODEL=$RERANK_MODEL"
      [ "${RAG_HYBRID:-false}" = "true" ] && vec="$vec
      - ENABLE_RAG_HYBRID_SEARCH=true"
    fi
  fi
  if [ "$ENABLE_EMBEDDINGS" = "true" ] && [ -z "${EMBED_URL:-}" ]; then
    model_update_env="      - RAG_EMBEDDING_MODEL_AUTO_UPDATE=True"
  else
    model_update_env="      - RAG_EMBEDDING_MODEL_AUTO_UPDATE=False
      - RAG_RERANKING_MODEL_AUTO_UPDATE=False
      - WHISPER_MODEL_AUTO_UPDATE=False"
  fi
  # Document extraction via Docling (structure/tables/formulas/OCR) when the ingest layer is on.
  local extract=""
  if ingest_enabled; then
    extract="      - CONTENT_EXTRACTION_ENGINE=docling
      - DOCLING_SERVER_URL=http://ingest-docling:5001"
  fi
  # Bundled Ollama is exposed through an auth proxy. Prefer OpenAI-compatible
  # /v1 so Authorization is attached consistently; native Ollama clients differ
  # on whether they send OLLAMA_API_KEY.
  local ollama_env=""
  ollama_enabled && ! llm_gateway_enabled && ollama_env="      - OPENAI_API_BASE_URL=http://ollama:11434/v1"
  # LiteLLM gateway → chat's OpenAI endpoint routes through it (cloud routing/fallback/budgets).
  local gateway_env=""
  llm_gateway_enabled && gateway_env="      - OPENAI_API_BASE_URL=http://litellm:4000/v1
      - OPENAI_API_KEY=sk-$(secret_get litellm_master_key admin_pw_gen)"
  # Auto-register the MCP server as an Open WebUI OpenAPI tool server (best-effort: the
  # env is read on first run by Open WebUI versions that support tool-server connections).
  local owui_tools=""
  if owui_bridge_enabled; then
    # Memory + gateway tools, bridged to OpenAPI by mcpo, registered as chat tool servers.
    owui_tools="      - 'TOOL_SERVER_CONNECTIONS=$(owui_tool_server_connections)'"
  elif [ "$ENABLE_MCP" = "true" ]; then
    owui_tools='      - '"'"'TOOL_SERVER_CONNECTIONS=[{"url":"http://mcp:9000","path":"openapi.json","auth_type":"none","key":"","config":{"enable":true}}]'"'"''
  fi
  cat >> "$(COMPOSE_FILE)" <<EOF

  openwebui:
    image: $OPENWEBUI_IMAGE
    container_name: ${SAFE_STACK_NAME}-openwebui
    restart: unless-stopped
    cap_drop: [ ALL ]
    security_opt: [ "no-new-privileges:true" ]
    env_file:
      - .runtime.env
    environment:
      - WEBUI_URL=$owui_url
      - CORS_ALLOW_ORIGIN=$cors_origins
      - WEBUI_SESSION_COOKIE_SECURE=$cookie_secure
      - WEBUI_AUTH_COOKIE_SECURE=$cookie_secure
      - WEBUI_SESSION_COOKIE_SAME_SITE=lax
      - WEBUI_AUTH_COOKIE_SAME_SITE=lax
      - FORWARDED_ALLOW_IPS=*
      - ENABLE_WEBSOCKET_SUPPORT=True
      - WEBUI_AUTH=True
      - ENABLE_LOGIN_FORM=True
      - ENABLE_SIGNUP=False
      - ENABLE_API_KEYS=True
      - ANONYMIZED_TELEMETRY=false
      - DO_NOT_TRACK=true
      - SCARF_NO_ANALYTICS=true
$model_update_env
$search
$vec
$extract
$ollama_env
$gateway_env
$owui_tools
$(stack_env_lines)
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:8080/api/config | jq -e '.status == true' >/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 300s
    volumes:
      - ../data/openwebui:/app/backend/data
EOF
}

compose_searxng() {
  [ "$ENABLE_SEARCH" = "true" ] || return 0
  cat >> "$(COMPOSE_FILE)" <<EOF

  searxng:
    image: $SEARXNG_IMAGE
    container_name: ${SAFE_STACK_NAME}-searxng
    restart: unless-stopped
    security_opt: [ "no-new-privileges:true" ]
    env_file:
      - .runtime.env
    environment:
      - SEARXNG_BASE_URL=http://searxng:8080/
    volumes:
      - ../data/searxng:/etc/searxng
EOF
}

compose_forgejo() {
  [ "$ENABLE_GIT" = "true" ] || return 0
  # In no-domain (pure localhost) mode bind git-SSH to loopback only; with domains (LAN/
  # public) it must stay reachable on all interfaces for git-over-SSH.
  local gitbind=""; no_domain && gitbind="127.0.0.1:"
  cat >> "$(COMPOSE_FILE)" <<EOF

  forgejo:
    image: $FORGEJO_IMAGE
    container_name: ${SAFE_STACK_NAME}-forgejo
    restart: unless-stopped
    security_opt: [ "no-new-privileges:true" ]
    environment:
      - USER_UID=$(id -u)
      - USER_GID=$(id -g)
      - FORGEJO____APP_NAME=$STACK_NAME Git
      - FORGEJO__server__DOMAIN=$GIT_DOMAIN
      - FORGEJO__server__SSH_DOMAIN=$GIT_SSH_HOST
      - FORGEJO__server__ROOT_URL=https://$GIT_DOMAIN/
      - FORGEJO__server__SSH_PORT=$GIT_SSH_PORT
      - FORGEJO__service__DISABLE_REGISTRATION=true
      - FORGEJO__service__REQUIRE_SIGNIN_VIEW=true
      - FORGEJO__session__COOKIE_SECURE=true
      - FORGEJO__repository__DEFAULT_PRIVATE=private
      - FORGEJO__actions__ENABLED=false
    volumes:
      - ../data/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "${gitbind}$GIT_SSH_PORT:22"
EOF
}

# Resolve the effective OpenHands docker mode. An explicit PSAI_OH_MODE always wins; otherwise
# untrusted deployments (public or multi-node) default to 'dind' (a nested daemon) instead of
# handing OpenHands the host's docker socket — host mode is effectively host-level control by
# the agent runtime. Single + local stays 'host' (simplest). Decided once at install and saved.
resolve_oh_mode() {
  [ "${ENABLE_AGENTS:-false}" = "true" ] || return 0
  [ "${OH_MODE_FROM_ENV:-0}" = "1" ] && return 0
  case "$OPENHANDS_DOCKER_MODE" in dind|rootless) return 0 ;; esac
  if [ "$DEPLOY_PROFILE" = "public" ] || [ "$NODE_MODE" = "multi" ]; then
    OPENHANDS_DOCKER_MODE="dind"
    printf '%sopenhands: untrusted deployment → docker mode = dind (nested daemon, not the host socket)%s\n' "$C_DIM" "$C_RESET" >&2
  fi
}

# Resolve PSAI_RAG into concrete component flags. plus = Qdrant + the local embed/rerank
# service + Docling/Tika ingest, with Open WebUI RAG and the MCP memory pointed at the local
# OpenAI-compatible embedder (replacing Open WebUI's built-in encoder and the MCP stub's
# keyword-only hash vectorizer). basic = Qdrant + Open WebUI's built-in embeddings. Decided
# at install and persisted, like resolve_oh_mode.
rag_uses_ollama_embeddings_default() {
  ollama_enabled || return 1
  [ -z "${PSAI_EMBED_URL:-}" ] || return 1
  [ -z "${PSAI_EMBED_SVC_MODEL:-}" ] || return 1
  [ -z "${PSAI_RERANK_MODEL:-}" ] || return 1
  rag_low_disk_for_heavy_rag && return 0
  detect_os 2>/dev/null || true
  case "${OS_TYPE:-unknown}:${ARCH_TYPE:-unknown}" in
    macos:*|linux:arm64) return 0 ;;
  esac
  return 1
}

rag_plus_hint_text() {
  if rag_low_disk_for_heavy_rag; then
    t q_rag_plus_hint_ollama_light
  elif rag_uses_ollama_embeddings_default; then
    t q_rag_plus_hint_ollama
  else
    t q_rag_plus_hint_infinity
  fi
}

resolve_rag_mode() {
  case "${RAG_MODE:-off}" in
    plus)
      ENABLE_QDRANT="true"; ENABLE_INGEST="true"
      rag_low_disk_for_heavy_rag && ENABLE_INGEST="false"
      if rag_uses_ollama_embeddings_default; then
        # Infinity's common image path is amd64-oriented; on macOS/arm64 and
        # Linux/arm64 it can end up behind emulation or unavailable. Use the
        # bundled Ollama OpenAI-compatible /v1/embeddings endpoint instead.
        ENABLE_EMBED_SVC="false"
        RERANK_MODEL=""
        [ -n "${EMBED_URL:-}" ]   || EMBED_URL="http://ollama:11434/v1"
        [ -n "${EMBED_MODEL:-}" ] || EMBED_MODEL="$OLLAMA_EMBED_MODEL"
      else
        ENABLE_EMBED_SVC="true"
      fi
      [ -n "${EMBED_URL:-}" ]   || EMBED_URL="http://embed:${EMBED_SVC_PORT:-7997}/v1"
      [ -n "${EMBED_MODEL:-}" ] || EMBED_MODEL="$EMBED_SVC_MODEL"
      if [ "${ENABLE_EMBED_SVC:-false}" = "true" ]; then
        printf '%s%s (%s)%s\n' "$C_DIM" "$(t rag_plus_infinity_note)" "$EMBED_SVC_MODEL" "$C_RESET" >&2
      elif [ "${ENABLE_INGEST:-false}" = "true" ]; then
        printf '%s%s (%s)%s\n' "$C_DIM" "$(t rag_plus_ollama_note)" "$EMBED_MODEL" "$C_RESET" >&2
      else
        printf '%s%s (%s)%s\n' "$C_DIM" "$(t rag_plus_ollama_light_note)" "$EMBED_MODEL" "$C_RESET" >&2
      fi ;;
    basic)
      ENABLE_QDRANT="true"; ENABLE_EMBEDDINGS="true" ;;
  esac
  return 0
}

# Bundled local LLM (Ollama) is on.
ollama_enabled() { [ "${LOCAL_LLM:-none}" = "ollama" ]; }
# Point the memory backend (cognee/graphiti) at the bundled Ollama when no external LLM
# endpoint was given — so memory works locally without a cloud API key. Embeddings also fall back to
# Ollama when RAG-plus's Infinity service isn't up.
resolve_local_llm() {
  ollama_enabled || return 0
  [ -n "${GPU_MODE:-}" ] || GPU_MODE="$(gpu_runtime)"   # autodetect for non-interactive installs
  if [ -z "${MEMORY_LLM_URL:-}" ]; then
    MEMORY_LLM_URL="http://ollama:11434/v1"
    [ -n "${MEMORY_LLM_KEY:-}" ] || MEMORY_LLM_KEY="ollama"   # OpenAI clients want a non-empty key
    MEMORY_LLM_MODEL="$OLLAMA_MODEL"
  fi
  printf '%sLLM: bundled Ollama · model: %s · memory endpoint: local%s\n' "$C_DIM" "$OLLAMA_MODEL" "$C_RESET" >&2
  return 0
}

# Docker MCP Gateway is on.
mcp_gateway_enabled() { [ "${MCP_GATEWAY:-false}" = "true" ]; }
mcp_gateway_sse_url() { mcp_gateway_enabled && printf 'http://mcp-gateway:%s/sse' "${MCP_GATEWAY_PORT:-8811}"; }

# A self-hosted memory backend (its own container) is up.
memory_self_host() { case "${MEMORY_MODE:-stub}" in cognee|graphiti) return 0 ;; *) return 1 ;; esac; }
# The SSE/MCP endpoint of the ACTIVE memory backend — seeded into OpenHands + Open WebUI so the
# agents and chat share one memory. cognee/graphiti run as the `memory` service; mem0 is cloud;
# stub is the built-in python MCP (mcp:9000).
memory_sse_url() {
  case "${MEMORY_MODE:-stub}" in
    cognee|graphiti) printf 'http://memory:%s/sse' "${MEMORY_PORT:-8000}" ;;
    mem0)            [ -n "${MEM0_MCP_URL:-}" ] && printf '%s' "$MEM0_MCP_URL" ;;
    *)               mcp_enabled && printf '%s' "${MCP_SSE_URL:-http://mcp:9000/sse}" ;;
  esac
}

disk_free_gb() {
  local path="${1:-.}" kb
  while [ ! -e "$path" ] && [ "$path" != "/" ]; do
    path="$(dirname "$path")"
  done
  kb="$(df -Pk "$path" 2>/dev/null | awk 'NR==2 {print $4; exit}')"
  case "$kb" in ''|*[!0-9]*) printf '0' ;; *) printf '%s' $((kb / 1048576)) ;; esac
}

rag_low_disk_for_heavy_rag() {
  [ "${PSAI_RAG_HEAVY_ALLOW:-false}" = "true" ] && return 1
  local min free
  min="${PSAI_RAG_HEAVY_MIN_FREE_GB:-55}"
  free="$(disk_free_gb "${STACK_DIR:-.}")"
  case "$min:$free" in
    *[!0-9:]*|:*) return 1 ;;
    *) [ "$free" -lt "$min" ] ;;
  esac
}

guard_cognee_disk() {
  [ "${MEMORY_MODE:-stub}" = "cognee" ] || return 0
  [ "${PSAI_COGNEE_ALLOW_HUGE:-false}" = "true" ] && return 0
  local min free path
  min="${PSAI_COGNEE_MIN_FREE_GB:-45}"
  path="${STACK_DIR:-.}"
  free="$(disk_free_gb "$path")"
  case "$min:$free" in *[!0-9:]*|:*) return 0 ;; esac
  if [ "$free" -lt "$min" ]; then
    printf '%s%s%s\n' "$C_YELLOW" "$(printf "$(t memory_cognee_disk_guard)" "$min" "$free")" "$C_RESET" >&2
    MEMORY_MODE="stub"
    ENABLE_MCP="true"
  fi
}

# Resolve PSAI_MEMORY. cognee/graphiti replace the keyword-only stub as the shared memory MCP.
resolve_memory_mode() {
  guard_cognee_disk
  case "${MEMORY_MODE:-stub}" in
    cognee|graphiti)
      ENABLE_MCP="false"   # the real memory backend is the MCP now — don't also run the stub
      printf '%sMemory: %s · self-host · LLM model: %s%s%s\n' "$C_DIM" "$MEMORY_MODE" \
        "$MEMORY_LLM_MODEL" "$([ -z "${MEMORY_LLM_KEY:-}" ] && printf ' (no LLM key yet — set PSAI_MEMORY_LLM_KEY)')" "$C_RESET" >&2 ;;
    mem0|none|stub) : ;;
    *) MEMORY_MODE="stub" ;;
  esac
  return 0
}

compose_openhands() {
  [ "$ENABLE_AGENTS" = "true" ] || return 0
  resolve_openhands_socket
  local sandbox_vols="$STACK_DIR/data/projects:/workspace:rw"
  local oh_docker_env="" oh_sock_vol="" oh_depends="" oh_model="" oh_mcp_vol=""
  if [ "$OPENHANDS_DOCKER_MODE" = "dind" ]; then
    # Share only the nested daemon's unix socket with OpenHands. The images keep
    # /var/run as a symlink to /run, so mount the shared volume on /run in both
    # containers; OpenHands still finds /var/run/docker.sock through the symlink.
    oh_docker_env="      - DOCKER_HOST=unix:///var/run/docker.sock"
    oh_sock_vol="      - dind-run:/run"
    oh_depends="    depends_on: [dind]"
  else
    oh_sock_vol="      - $DOCKER_SOCK:/var/run/docker.sock"
    # Mounting the host docker socket INTO the agent sandbox = host root for agent-authored
    # code. AGENTS_DOCKER is an explicit operator override, so allow it but warn hard on public.
    if [ "$AGENTS_DOCKER" = "true" ]; then
      sandbox_vols="$sandbox_vols,$DOCKER_SOCK:/var/run/docker.sock"
      [ "$DEPLOY_PROFILE" = "public" ] && printf '%s%s%s\n' "$C_YELLOW" "$(t agents_docker_public_warn)" "$C_RESET" >&2
    fi
  fi
  [ -n "${OPENHANDS_LLM_MODEL:-}" ] && oh_model="      - LLM_MODEL=$OPENHANDS_LLM_MODEL"
  openhands_mcp_config_active && oh_mcp_vol="      - ../openhands-config/config.toml:/app/config.toml:ro"
  cat >> "$(COMPOSE_FILE)" <<EOF

  openhands:
    image: $OPENHANDS_IMAGE
    container_name: ${SAFE_STACK_NAME}-openhands
    restart: unless-stopped
    pull_policy: missing
    # NB: OpenHands is an agent runtime that manages users + spawns sandbox
    # containers via the docker socket — it must keep its capabilities. Dropping
    # them (cap_drop ALL) strips CAP_DAC_OVERRIDE and root can't even stat its own
    # /app/entrypoint.sh ("permission denied" at runc init). The stateless services
    # (openwebui/searxng/caddy) stay locked down; this one cannot be.
$oh_depends
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=${SAFE_STACK_NAME}_${OPENHANDS_SANDBOX_IMAGE_SUFFIX}
      - SANDBOX_VOLUMES=$sandbox_vols
      - SANDBOX_USER_ID=$(id -u)
      - WORKSPACE_MOUNT_PATH=$STACK_DIR/data/projects
      - WORKSPACE_BASE=/workspace
      - SANDBOX_ENABLE_GPU=false
      - SEARXNG_INSTANCE=http://searxng:8080
      - LOG_ALL_EVENTS=true
      - DO_NOT_TRACK=true
$oh_model
$oh_docker_env
$(stack_env_lines)
    volumes:
$oh_sock_vol
$oh_mcp_vol
      - ../data/openhands-state:/.openhands
      - ../data/projects:/workspace
EOF
  if [ "$OPENHANDS_DOCKER_MODE" = "dind" ]; then
    cat >> "$(COMPOSE_FILE)" <<EOF

  dind:
    image: $DIND_IMAGE
    container_name: ${SAFE_STACK_NAME}-dind
    privileged: true
    restart: unless-stopped
    command:
      - dockerd
      - --host=unix:///var/run/docker.sock
      - --storage-driver=overlay2
    environment:
      - DOCKER_TLS_CERTDIR=
$(stack_env_lines)
    volumes:
      - dind-data:/var/lib/docker
      - dind-run:/run
      - ../openhands-sandbox:/psai-openhands-sandbox:ro
      - $STACK_DIR/data/projects:$STACK_DIR/data/projects
EOF
  fi
}

# Assemble the whole compose file.
write_compose() {
  compose_header
  compose_caddy
  compose_openwebui
  compose_searxng
  compose_forgejo
  compose_openhands
  append_qdrant_service
  append_embed_service
  append_ingest_service
  append_mcp_service
  append_cognee_service
  append_graphiti_service
  append_ollama_service
  append_mcp_gateway_service
  append_mcpo_service
  append_litellm_service
  append_eval_service
  append_pentest_service
  append_proxy_service stack
  append_proxy_service web
  append_ollama_networks
  append_named_volumes
}

append_named_volumes() {
  { [ "${ENABLE_AGENTS:-false}" = "true" ] && [ "${OPENHANDS_DOCKER_MODE:-host}" = "dind" ]; } || return 0
  cat >> "$(COMPOSE_FILE)" <<'EOF'

volumes:
  dind-data:
  dind-run:
EOF
}

# ───────────────────────────── OpenHands sandbox ─────────────────────────────
write_openhands_sandbox_dockerfile() {
  local flavor
  flavor="${PSAI_OPENHANDS_SANDBOX_FLAVOR:-lite}"
  case "$flavor" in
    full|heavy)
      cat > "$STACK_DIR/openhands-sandbox/Dockerfile" <<'EOF'
FROM nikolaik/python-nodejs:python3.12-nodejs22
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
RUN apt-get update && apt-get install -y --no-install-recommends \
    bash ca-certificates curl wget git git-lfs openssh-client jq \
    ripgrep fd-find unzip zip p7zip-full build-essential cmake make \
    pkg-config sqlite3 shellcheck docker.io docker-compose \
    && rm -rf /var/lib/apt/lists/*
RUN python -m pip install --no-cache-dir --upgrade \
    pip setuptools wheel virtualenv pipx uv \
    numpy pandas scipy pytest ruff black mypy bandit pip-audit \
    requests httpx[socks] pysocks beautifulsoup4 lxml playwright
RUN python -m playwright install --with-deps chromium || python -m playwright install chromium || true
RUN npm install -g --force pnpm typescript tsx eslint prettier yarn
WORKDIR /workspace
EOF
      ;;
    *)
      cat > "$STACK_DIR/openhands-sandbox/Dockerfile" <<'EOF'
FROM nikolaik/python-nodejs:python3.12-nodejs22
SHELL ["/bin/bash", "-euo", "pipefail", "-c"]
WORKDIR /workspace
EOF
      ;;
  esac
  compute_egress_endpoints
  if egress_web_enabled && web_via_proxy; then
    sandbox_proxy_env_lines >> "$STACK_DIR/openhands-sandbox/Dockerfile"
  fi
}

build_openhands_sandbox() {
  [ "$ENABLE_AGENTS" = "true" ] || return 0
  write_openhands_sandbox_dockerfile
  local img
  img="${SAFE_STACK_NAME}_${OPENHANDS_SANDBOX_IMAGE_SUFFIX}"
  if [ "${OPENHANDS_DOCKER_MODE:-host}" = "dind" ]; then
    docker image inspect "$img" >/dev/null 2>&1 \
      || build_openhands_sandbox_image "$img" \
      || true
    return 0
  fi
  build_openhands_sandbox_image "$img"
}

build_openhands_sandbox_image() {
  local img="$1" timeout rc
  timeout="${PSAI_SANDBOX_BUILD_TIMEOUT:-1800}"

  # Prefer BuildKit: the legacy builder can hang while committing the large
  # Playwright/browser layer even after the build container exits cleanly.
  run_with_timeout "$timeout" env DOCKER_BUILDKIT=1 docker build -t "$img" "$STACK_DIR/openhands-sandbox"
  rc=$?
  if [ "$rc" -eq 0 ]; then
    return 0
  fi
  printf '%sopenhands sandbox: BuildKit build failed (rc=%s), retrying with legacy builder%s\n' "$C_YELLOW" "$rc" "$C_RESET" >&2
  run_with_timeout "$timeout" env DOCKER_BUILDKIT=0 docker build -t "$img" "$STACK_DIR/openhands-sandbox"
}

wait_dind_ready() {
  [ "$ENABLE_AGENTS" = "true" ] || return 0
  [ "${OPENHANDS_DOCKER_MODE:-host}" = "dind" ] || return 0
  local i
  i=0
  while [ "$i" -lt 90 ]; do
    if compose exec -T dind docker info >/dev/null 2>&1; then return 0; fi
    sleep 2
    i=$((i + 1))
  done
  return 1
}

build_openhands_sandbox_dind() {
  [ "$ENABLE_AGENTS" = "true" ] || return 0
  [ "${OPENHANDS_DOCKER_MODE:-host}" = "dind" ] || return 0
  local img
  img="${SAFE_STACK_NAME}_${OPENHANDS_SANDBOX_IMAGE_SUFFIX}"
  write_openhands_sandbox_dockerfile
  wait_dind_ready || return 1
  if ! compose exec -T dind docker image inspect "$img" >/dev/null 2>&1; then
    if docker image inspect "$img" >/dev/null 2>&1; then
      docker save "$img" | compose exec -T dind docker load
    else
      compose exec -T dind docker build -t "$img" /psai-openhands-sandbox
    fi
  fi
  compose exec -T dind docker image inspect "$img" >/dev/null
  compose up -d --force-recreate --no-deps openhands
}

select_openhands_image() {
  [ "$ENABLE_AGENTS" = "true" ] || return 0
  if [ -n "${OPENHANDS_IMAGE_DEFAULT:-}" ]; then OPENHANDS_IMAGE="$OPENHANDS_IMAGE_DEFAULT"; return 0; fi
  if [ -n "${OPENHANDS_IMAGE:-}" ] && docker image inspect "$OPENHANDS_IMAGE" >/dev/null 2>&1; then return 0; fi
  local v="${OPENHANDS_VERSION:-1.8.0}" img
  for img in \
    "ghcr.io/all-hands-ai/openhands:$v" \
    "docker.all-hands.dev/all-hands-ai/openhands:$v" \
    "ghcr.io/openhands/openhands:$v"; do
    if docker pull "$img" >/dev/null 2>&1; then OPENHANDS_IMAGE="$img"; return 0; fi
  done
  printf '%s\n' "OpenHands $v not found; falling back to :latest (UNPINNED)." >&2
  for img in \
    "ghcr.io/all-hands-ai/openhands:latest" \
    "docker.all-hands.dev/all-hands-ai/openhands:latest"; do
    if docker pull "$img" >/dev/null 2>&1; then OPENHANDS_IMAGE="$img"; return 0; fi
  done
  echo 'OpenHands image pull failed.'; return 1
}

# ───────────────────────────── self-copy + PATH link ─────────────────────────────
copy_self_into_stack() {
  local bindir="$STACK_DIR/bin" dest old
  mkdir -p "$bindir"; dest="$bindir/$MGMT_NAME"
  old="$(legacy_mgmt_name)"
  [ "$old" = "$MGMT_NAME" ] || rm -f "$bindir/$old" 2>/dev/null || true
  # Don't clobber ourselves when invoked from the installed copy (rebuild/update):
  # rm+cp would delete the running script and the cp source would vanish.
  if ! [ "$SCRIPT_PATH" -ef "$dest" ] 2>/dev/null; then
    rm -f "$dest"; cp "$SCRIPT_PATH" "$dest"; chmod +x "$dest"
  fi
  command -v write_python_dashboard >/dev/null 2>&1 && write_python_dashboard || true
  link_command_on_path "$dest"
}

# Force Caddy to reload after a config change. A plain `compose up -d` leaves an
# unchanged caddy service running with its old in-memory config; force-recreate
# makes a fresh container that reads the regenerated Caddyfile.
reload_caddy() { compose up -d --force-recreate --no-deps caddy >/dev/null 2>&1 || true; }
legacy_mgmt_name() { printf '%s_%s' ai stack; }
remove_legacy_command_links() {
  local old d
  old="$(legacy_mgmt_name)"
  [ "$old" = "$MGMT_NAME" ] && return 0
  for d in /opt/homebrew/bin /usr/local/bin "$HOME/.local/bin" "$HOME/bin"; do
    [ -L "$d/$old" ] && rm -f "$d/$old" 2>/dev/null || true
  done
}
link_command_on_path() {
  local src="$1" d sudo_cmd=""
  remove_legacy_command_links
  for d in /opt/homebrew/bin /usr/local/bin "$HOME/.local/bin" "$HOME/bin"; do
    [ -d "$d" ] && [ -w "$d" ] && ln -sf "$src" "$d/$MGMT_NAME" 2>/dev/null && return 0
  done
  [ "$(id -u)" = "0" ] || sudo_cmd="sudo"
  if can_use_sudo && [ -d /usr/local/bin ]; then
    $sudo_cmd ln -sf "$src" "/usr/local/bin/$MGMT_NAME" 2>/dev/null && return 0
  fi
  mkdir -p "$HOME/.local/bin" 2>/dev/null && ln -sf "$src" "$HOME/.local/bin/$MGMT_NAME" 2>/dev/null && return 0
  return 0
}

run_with_timeout() {
  local seconds="$1" pid i rc
  shift
  case "$seconds" in ''|*[!0-9]*) seconds=0 ;; esac
  [ "$seconds" -le 0 ] && { "$@"; return $?; }
  "$@" &
  pid=$!
  i=0
  while kill -0 "$pid" 2>/dev/null; do
    if [ "$i" -ge "$seconds" ]; then
      kill_process_tree TERM "$pid"
      sleep 2
      kill_process_tree KILL "$pid"
      wait "$pid" 2>/dev/null || true
      return 124
    fi
    sleep 1
    i=$((i + 1))
  done
  rc=0; wait "$pid" || rc=$?
  return $rc
}

kill_process_tree() {
  local signal="$1" pid="$2" child
  if command -v pgrep >/dev/null 2>&1; then
    for child in $(pgrep -P "$pid" 2>/dev/null || true); do
      kill_process_tree "$signal" "$child"
    done
  fi
  kill "-$signal" "$pid" 2>/dev/null || true
}

compose_up_core() {
  local services core s rc
  if ! ingest_enabled; then
    compose up -d --build --remove-orphans
    rc=$?
    [ "$rc" -eq 0 ] && build_openhands_sandbox_dind
    return $rc
  fi
  services="$(compose config --services 2>/dev/null || true)"
  core=""
  for s in $services; do
    case "$s" in ingest-docling|ingest-tika) ;; *) core="$core $s" ;; esac
  done
  # shellcheck disable=SC2086
  if [ -n "$core" ]; then compose up -d --build --remove-orphans $core
  else compose up -d --build --remove-orphans; fi
  rc=$?
  [ "$rc" -eq 0 ] && build_openhands_sandbox_dind
  return $rc
}

pull_component_images() {
  local images img total i=0
  images="$(compose config --images 2>/dev/null | sort -u | sed '/^$/d')" || images=""
  images="$(printf '%s\n' "$images" | grep -v -E "^(${SAFE_STACK_NAME}-mcp:|${SAFE_STACK_NAME}-pentest:|${SAFE_STACK_NAME}_)" || true)"
  [ -n "$images" ] || return 0
  total="$(printf '%s\n' "$images" | wc -l | tr -d ' ')"
  while IFS= read -r img; do
    [ -n "$img" ] || continue
    i=$((i + 1))
    printf '  %s[%d/%d]%s %s' "$C_DIM" "$i" "$total" "$C_RESET" "$img"
    if docker image inspect "$img" >/dev/null 2>&1; then
      printf ' %s%s%s\n' "$C_GREEN" "present" "$C_RESET"
    elif pull_component_image "$img" "$i" "$total"; then
      printf ' %s%s%s\n' "$C_GREEN" "pulled" "$C_RESET"
    else
      printf ' %s%s%s\n' "$C_RED" "failed" "$C_RESET"
      return 1
    fi
  done <<EOF
$images
EOF
}

pull_component_image() {
  local img="$1" i="$2" total="$3" log pid rc spin ch n=0
  log="${TMPDIR:-/tmp}/psai-pull-${SAFE_STACK_NAME:-stack}-$$.log"
  docker pull -q "$img" >"$log" 2>&1 &
  pid=$!
  spin='-\|/'
  while kill -0 "$pid" 2>/dev/null; do
    n=$((n + 1))
    ch="$(printf '%s' "$spin" | cut -c "$((n % 4 + 1))")"
    printf '\r  %s[%d/%d]%s %s %s%s%s' "$C_DIM" "$i" "$total" "$C_RESET" "$img" "$C_CYAN" "$ch" "$C_RESET"
    sleep 0.2
  done
  wait "$pid"; rc=$?
  printf '\r  %s[%d/%d]%s %s' "$C_DIM" "$i" "$total" "$C_RESET" "$img"
  if [ "$rc" -ne 0 ]; then
    printf '\n%s' "$C_DIM" >&2
    tail -20 "$log" >&2 || true
    printf '%s' "$C_RESET" >&2
  fi
  rm -f "$log" 2>/dev/null || true
  return "$rc"
}

run_pull_step() {
  local prefix=""
  if [ "$STEP_TOTAL" -gt 0 ]; then
    STEP_NUM=$((STEP_NUM + 1))
    prefix="$(printf '%s[%d/%d]%s ' "$C_DIM" "$STEP_NUM" "$STEP_TOTAL" "$C_RESET")"
  fi
  printf '%s%s …\n' "$prefix" "$(t step_pull)"
  pull_component_images
}

compose_up_ingest() {
  ingest_enabled || return 0
  run_with_timeout "${PSAI_INGEST_START_TIMEOUT:-900}" compose up -d --no-deps ingest-docling ingest-tika
}

prune_disabled_services() {
  local rm=""
  [ "$ENABLE_OPENWEBUI" = "true" ] || rm="$rm openwebui"
  [ "$ENABLE_SEARCH"    = "true" ] || rm="$rm searxng"
  [ "$ENABLE_GIT"       = "true" ] || rm="$rm forgejo"
  [ "$ENABLE_AGENTS"    = "true" ] || rm="$rm openhands"
  [ "$ENABLE_QDRANT"    = "true" ] || rm="$rm qdrant"
  embed_enabled  || rm="$rm embed"
  ingest_enabled || rm="$rm ingest-docling ingest-tika"
  memory_self_host || rm="$rm memory falkordb"
  ollama_enabled || rm="$rm ollama ollama-raw ollama-pull"
  mcp_gateway_enabled || rm="$rm mcp-gateway"
  owui_bridge_enabled || rm="$rm mcpo"
  llm_gateway_enabled || rm="$rm litellm"
  eval_enabled || rm="$rm langfuse langfuse-db"
  mcp_enabled || rm="$rm mcp"
  egress_stack_enabled || rm="$rm proxy-stack"
  egress_web_enabled   || rm="$rm proxy-web proxy-web-http"
  # shellcheck disable=SC2086
  [ -n "$rm" ] && compose rm -sf $rm >/dev/null 2>&1 || true
}

# ───────────────────────────── orchestrator ─────────────────────────────
write_all_configs() {
  resolve_eg_host_web_port
  type avoid_local_caddy_port_conflict >/dev/null 2>&1 && avoid_local_caddy_port_conflict
  save_config
  # Bring up stack-vault first so generated secrets go into RAM, not a file on disk.
  # If the vault is required (strict) but can't unseal, fail rather than silently
  # writing plaintext secrets to disk.
  if vault_enabled; then
    vault_present || build_vault || true
    vault_start || { printf '%svault required but not unsealed — aborting%s\n' "$C_RED" "$C_RESET" >&2; return 1; }
  fi
  prepare_dirs_and_secrets
  compute_egress_endpoints
  configure_egress_secrets stack
  configure_egress_secrets web
  compute_egress_endpoints
  write_searxng_settings
  write_mcp_stub
  write_ollama_proxy_files
  write_litellm_config
  write_pentest_dockerfile
  write_openhands_mcp_config
  write_mcpo_config
  generate_local_ca_and_cert
  select_openhands_image
  save_config
  write_caddyfile
  render_runtime_env
  write_compose
  copy_self_into_stack
  reseal_blob
}

# Reversible runtime secrets the containers need (session keys), kept OUT of the
# compose file. Rendered from the vault and SHREDDED on stop, so when the stack is
# sealed no secret value persists on disk — only the encrypted vault blob does.
# Zero-disk: on Linux the file is backed by tmpfs (/dev/shm) with a symlink in compose/,
# so the plaintext session keys live in RAM, never on the SSD.
runtime_env_file()   { printf '%s/compose/.runtime.env' "$STACK_DIR"; }
# Private, per-uid tmpfs dir (0700) — NOT a predictable file directly under the world-
# writable /dev/shm. A local attacker can't plant a symlink inside a 0700 dir we own, and
# runtime_tmpfs_prepare refuses if the dir was pre-created by someone else.
runtime_tmpfs_dir()  { printf '/dev/shm/.psai-%s' "$(id -u)"; }
runtime_tmpfs_path() { printf '%s/%s.runtime.env' "$(runtime_tmpfs_dir)" "${SAFE_STACK_NAME:-psai}"; }
runtime_use_tmpfs() {
  [ "${RUNTIME_TMPFS:-true}" = "true" ] || return 1
  detect_os 2>/dev/null || true
  [ "${OS_TYPE:-}" = "linux" ] && [ -d /dev/shm ]
}
# Ensure the private tmpfs dir exists and is ours. Returns 1 (→ caller falls back to the
# on-disk 0600 file) if it exists but isn't a plain directory we own.
runtime_tmpfs_prepare() {
  local d; d="$(runtime_tmpfs_dir)"
  if [ -e "$d" ] || [ -L "$d" ]; then
    { [ -d "$d" ] && [ ! -L "$d" ] && [ -O "$d" ]; } || {
      printf '%sruntime: %s not a dir we own — using on-disk env%s\n' "$C_YELLOW" "$d" "$C_RESET" >&2; return 1; }
  else
    mkdir -m 700 "$d" 2>/dev/null || return 1
  fi
  chmod 700 "$d" 2>/dev/null || true
}
render_runtime_env() {
  mkdir -p "$STACK_DIR/compose"
  local target; target="$(runtime_env_file)"
  if runtime_use_tmpfs && runtime_tmpfs_prepare; then
    target="$(runtime_tmpfs_path)"
    rm -f "$target" 2>/dev/null || true            # drop any planted file/symlink (we own the 0700 parent)
    rm -f "$(runtime_env_file)" 2>/dev/null || true
    ln -sf "$target" "$(runtime_env_file)"         # compose env_file follows the symlink into RAM
  fi
  # Never write THROUGH an unexpected symlink at the real target (the on-disk path).
  if [ -L "$target" ]; then
    printf '%sruntime: refusing to write through symlink %s%s\n' "$C_YELLOW" "$target" "$C_RESET" >&2; return 1
  fi
  # NOTE: SEARXNG_SECRET is intentionally NOT emitted here — the searxng base image
  # never consumes it. SearXNG's session key is written straight into settings.yml by
  # write_searxng_settings (from the same vault secret). Only WEBUI_SECRET_KEY is a real
  # runtime env consumed by its container.
  ( umask 077; {
      printf '# generated from stack-vault — shredded on stop, do not commit\n'
      if [ "$ENABLE_OPENWEBUI" = "true" ]; then
        printf 'WEBUI_SECRET_KEY=%s\n' "$(secret_get webui_secret)"
      fi
      if ollama_enabled; then
        local ok; ok="$(secret_get ollama_api_key api_key_gen)"
        printf 'OLLAMA_API_KEY=%s\n' "$ok"
        [ "${LLM_GATEWAY:-false}" = "true" ] || printf 'OPENAI_API_KEY=%s\n' "$ok"
        case "${EMBED_URL:-}" in
          http://ollama:11434*) printf 'RAG_OPENAI_API_KEY=%s\nEMBED_API_KEY=%s\n' "$ok" "$ok" ;;
        esac
        case "${MEMORY_MODE:-stub}" in
          cognee) printf 'LLM_API_KEY=%s\n' "$ok" ;;
          graphiti) printf 'OPENAI_API_KEY=%s\n' "$ok" ;;
        esac
      elif [ -n "${EMBED_API_KEY:-}" ]; then
        printf 'RAG_OPENAI_API_KEY=%s\n' "$EMBED_API_KEY"
      fi
      # Pinned MCP gateway token — the gateway requires it, and OpenHands + mcpo present it.
      mcp_gateway_enabled && printf 'MCP_GATEWAY_AUTH_TOKEN=%s\n' "$(secret_get mcp_gateway_token api_key_gen)"
      true
    } > "$target" )
  chmod 600 "$target" 2>/dev/null || true
}
shred_runtime_env() {
  local link f; link="$(runtime_env_file)"; f="$link"
  [ -L "$link" ] && f="$(readlink "$link" 2>/dev/null)"
  for x in "$f" "$link"; do
    [ -n "$x" ] || continue
    rm -P "$x" 2>/dev/null || shred -u "$x" 2>/dev/null || rm -f "$x" 2>/dev/null || true
  done
}
